#!/bin/bash

# List of required services
SERVICES=(jenkins postfix)

# Check each service
for SERVICE in "${SERVICES[@]}"; do
  if systemctl status $SERVICE > /dev/null; then
    echo "$SERVICE is running"
  else
    echo "$SERVICE is not running"
    sudo systemctl start $SERVICE
  fi
done
